title: Virtual Research Institute
description: Mentored Research in Mathematics and Computational Sciences.
baseurl: ""
url: ""
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: "assets/images/research-archive"
    values:
      research_archive_slide: true
